[package]
name = "dynamodb"
description = "RAWS DynamoDB component"

authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
clap.workspace = true
miette.workspace = true
aws-sdk-dynamodb.workspace = true

config.workspace = true
