[package]
name = "config"
description = "RAWS config component"

authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
aws-config = "0.55"
aws-types = "0.55"

clap.workspace = true
show.workspace = true


[lints]
workspace = true
