[package]
name = "raws"
version = "0.1.0"
edition = "2021"
description = "AWS CLI"


[dependencies]
bytes = "1.4"
clap = { version = "4.2", features = ["derive", "env"] }
miette = { version = "5.5", features = ["fancy"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.26", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
uuid = { version = "1.3", features = ["serde"] }
