[package]
name = "raws"
description = "AWS CLI"

authors.workspace = true
version.workspace = true
edition.workspace = true
license.workspace = true


[dependencies]
bytes = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.26", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "time"] }
uuid = { version = "1.3", features = ["serde"] }

clap.workspace = true
miette.workspace = true

config.workspace = true
dynamodb = { version = "0.0", path = "../dynamodb" }
